[profile.default]
src = 'src'
out = 'out'
libs = ['dependencies']
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]
script = "script"
force = true
evm_version = 'paris'
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
multiline_func_header = 'params_first'
single_line_statement_blocks = "multi"


[dependencies]
"@openzeppelin-contracts-upgradeable" = "5.0.2"
"@openzeppelin-contracts" = "5.0.2"
forge-std = "1.9.2"
