[workspace]
members = [
    "src/bitfinity-benchmark",
    "src/create_bft_bridge_tool",
    "src/minter-contract-utils",
    "src/integration-tests",
    "src/minter-canister",
    # "src/evm-minter",
    "src/spender-canister",
    "src/solidity-helper",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"

[workspace.dependencies]
alloy-sol-types = "0.4"
anyhow = "1.0"
async-trait = "0.1"
auto_impl = "1.0"
axum = "0.6"
axum-test = "13"
bytes = "1.3"
candid = "0.9"
criterion = "0.5"
clap = { version = "4", features = ["derive"] }
csv = "1.1"
debug-ignore = "1.0.5"
derive_more = "0.99"
did = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "did", branch = "task_manager_branch_dependency" }
elsa = "1.7"
env_logger = { version = "0.10.0", default-features = false }
eth-signer = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "eth-signer", branch = "task_manager_branch_dependency" }
ethereum-json-rpc-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "ethereum-json-rpc-client", branch = "task_manager_branch_dependency" }
iceth_client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "iceth-client", branch = "task_manager_branch_dependency" }
evm-canister-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "evm-canister-client", branch = "task_manager_branch_dependency" }
minter-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "minter-client", branch = "task_manager_branch_dependency" }
minter-did = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "minter-did", branch = "task_manager_branch_dependency" }
register-evm-agent = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "register_evm_agent", branch = "task_manager_branch_dependency" }
signature-verification-canister-client = { git = "https://github.com/bitfinity-network/bitfinity-evm-sdk", package = "signature-verification-canister-client", branch = "task_manager_branch_dependency" }
ethers-core = "2.0"
ethereum-types = "0.14"
flate2 = "1"
futures = { version = "0.3", default-features = false }
hash-db = "0.15"
hashbrown = { version = "0.14" }
hex = "0.4"
ic-canister = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-canister", branch = "EPROD-641_task_processor" }
ic-exports = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-exports", branch = "EPROD-641_task_processor" }
ic-helpers = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-helpers", branch = "EPROD-641_task_processor" }
ic-log = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-log", branch = "EPROD-641_task_processor" }
ic-canister-client = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-canister-client", branch = "EPROD-641_task_processor" }
ic-metrics = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-metrics", branch = "EPROD-641_task_processor", features = [
    "export-api",
] }
ic-storage = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-storage", branch = "EPROD-641_task_processor" }
ic-stable-structures = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-stable-structures", branch = "EPROD-641_task_processor" }
ic-test-utils = { git = "https://github.com/bitfinity-network/canister-sdk", package = "ic-test-utils", branch = "EPROD-641_task_processor" }
jsonrpc-core = "18.0"
k256 = { version = "0.13", default-features = false }
lightspeed_scheduler = "0.55"
log = "0.4"
murmur3 = "0.5"
mockall = "0.11"
once_cell = "1.16"
parking_lot = "0.12.1"
plain_hasher = "0.2"
proptest = { version = "1.1.0", default-features = false, features = ["std"] }
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
rayon = "1"

reqwest = { version = "0.11", default-features = false }
revm = { version = "3.4", default-features = false, features = [
    "optional_eip3607", "serde"
] }
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
serde_with = "3.3"
smallvec = "1.10.0"
stable_deref_trait = "1.2"
rlp = "0.5"
sha2 = "0.10"
sha3 = "0.10"
tar = "0.4"
thiserror = "1.0"
tempfile = "3.8"
tokio = { version = "1.24", features = ["macros", "rt"] }
tokio-util = { version = "0.7" }
triehash = "0.8"
vergen = { version = "8.1", default-features = false, features = ["build", "cargo", "rustc", "si"] }
walkdir = "2"

[profile.dev]
debug = false

# Set the settings for all dependencies (but not this crate itself or any workspace member).
# This includes build dependencies.
# Level range is from 0 (default for dev) to 3 (default for release)
[profile.dev.package."*"]
opt-level = 2

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 2

[profile.release]
#opt-level = "z"
lto = true
codegen-units = 1
