name: "Reinstall canister"

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-deploy:
    uses: ./.github/workflows/build-deploy-canister.yml
    with:
      installation-method: reinstall
    secrets:
      EVM_DEPLOYER: ${{ secrets.EVM_DEPLOYER }}
      GH_PKG_LOGIN: ${{ secrets.GH_PKG_LOGIN }}
      GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  dispatch-event:
    name: "Dispatch event"
    runs-on: ubuntu-22.04
    needs: build-test-deploy
    steps:
      - name: "Dispatch event"
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.GH_PKG_TOKEN }}
          repository: bitfinity-network/evm-deployments
          event-type: deploy-contracts
