name: 'Publish evm-archiver release'

on:
  workflow_dispatch: {}

jobs:
  release-binaries:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: evm-archiver

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: evm-archiver.exe

          - release_for: MacOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: evm-archiver

          - release_for: MacOS-M1
            os: macos-latest
            target: aarch64-apple-darwin
            bin: evm-archiver

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          command: build
          strip: true
          args: '--release -p evm-archiver'

      - name: Prepare artifact files
        run: |
          mkdir -p ./target/artifact
          mv target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} ./target/artifact/${{ matrix.platform.bin }}

      - name: 'Uploading artifact'
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          retention-days: 1
          name: ${{ matrix.platform.release_for }}
          path: ./target/artifact/*

  publish-release:
    needs: [release-binaries]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          path: ./evm-canister

      - name: Checkout evm-archiver
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PKG_TOKEN }}
          repository: ${{ github.repository_owner }}/evm-archiver
          path: ./evm-archiver

      - id: version
        run: |
          cd ./evm-canister

          V_TOML=$(awk -F= '{gsub(/[ \t]+/, "", $1); gsub(/[ \t"]+/, "", $2); if($1 == "version"){print $2}}' ./Cargo.toml )  
          echo "toml=$V_TOML" >> $GITHUB_OUTPUT
          
          V_GIT=$(git describe --tag)
          echo "tag=$V_GIT" >> $GITHUB_OUTPUT
 
      - name: 'Artifact Linux'
        uses: actions/download-artifact@v3
        with:
          name: Linux-x86_64
          path: ./linux

      - name: 'Artifact MacOs'
        uses: actions/download-artifact@v3
        with:
          name: MacOS-x86_64
          path: ./macos

      - name: 'Artifact MacOs M1'
        uses: actions/download-artifact@v3
        with:
          name: MacOS-M1
          path: ./macos-m1

      - name: 'Artifact Windows'
        uses: actions/download-artifact@v3
        with:
          name: Windows-x86_64
          path: ./win

      - name: 'Prepare files'
        run: |
          # Updating Readme
          cp -f ./evm-canister/src/evm-archiver/README.md ./evm-archiver/README.md

          # Pack release files
          mkdir -p .release
          cd .release

          mv ../linux/evm-archiver ./evm-archiver-linux64
          mv ../macos/evm-archiver ./evm-archiver-darwin
          mv ../macos-m1/evm-archiver ./evm-archiver-m1
          mv ../win/evm-archiver.exe .

          ls -lah .

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Updating readme'
          add: '*.md --force'
          cwd: './evm-archiver/'

      - name: Releasing
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_PKG_TOKEN }}
          repository: ${{ github.repository_owner }}/evm-archiver
          # tag_name: ${{ steps.version.outputs.toml }}
          tag_name: ${{ steps.version.outputs.tag }}
          files: |
            .release/*

